export const SHOW_CATEGORY_MODAL = "SHOW_CATEGORY_MODAL";
export const HIDE_CATEGORY_MODAL = "HIDE_CATEGORY_MODAL";
export const SHOW_BUDGET_ITEM_MODAL = "SHOW_BUDGET_ITEM_MODAL";
export const HIDE_BUDGET_ITEM_MODAL = "HIDE_BUDGET_ITEM_MODAL";
