export const SHOW_CATEGORY_MODAL = "SHOW_CATEGORY_MODAL";
export const HIDE_CATEGORY_MODAL = "HIDE_CATEGORY_MODAL";
export const SHOW_BUDGET_ITEM_MODAL = "SHOW_BUDGET_ITEM_MODAL";
export const HIDE_BUDGET_ITEM_MODAL = "HIDE_BUDGET_ITEM_MODAL";

export const EDIT_CATEGORY_DATA = "EDIT_CATEGORY_DATA";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const SET_BUDGET_ITEMS = "SET_BUDGET_ITEMS";
